# 3 Cs of covalent bondas

## Shape of biological molecules 

- Folding 
- stability 

## Recognition and function of biological molecules 

- binding 
- interactions 

## Macromolecular Building Blocks 

- aminoácidos
- nucleótidos 
- carbohidratos 
- ácidos grasos 

## video DNA

- DNA B es el más común 
- nitrogeno en el carbono 1 
- 10 pares de bases por vuelta de la hélice 
- pi-pi interactions 

- 2 tipos de información que se pueden leer del DNA 
- puentes de H se forman entre átomos de cargas distintas cuando hay un momemnto dipolo fuerte 
    - Interacciones transitorias
    - Deslocalización de los electrones 

[3D structure DNA ](http://biomodel.uah.es/model4/dna/index.htm)
o
[Estructura secundaria del DNA](http://biomodel.uah.es/model1j/dna/b-dna.htm)

- naranja phosphatos 
- azul nitrogenos 
- gris carbono 
- blanco hidrogeno 
- amarillo azufre 
- cafe hierro


## Evolutivamente 

El RNA fue primero por su autocatálisis 

# XDS.INP  

```bash
scp XDS.INP avarela@tepeu.lcg.unam.mx:/export/storage/users/avarela

# Ejecutar la lectura 
xds_par 

```

```
UNIT_CELL_CONSTANTs= 38.9380 377.0
JOB
x-ray_wavelength = longitud de onda  al que le disparamos 
- datos de donde a 
- detector parametro para que no se sobrecargue 
- exlclye la resolución tal porque hay un aro de hielo 
```
Protein cristal fishing 
- pescas el cristal y lo metes en nitrógeno líquido 
- ice ring diffraction pattern se ve como un aro al disparar 
    - tienes que excluirla de tu análisis 
    - solo trabajas con el cristal si tiene hielo si no tienes de otra 
    - 



- el grupo espacial entre más alto sea tiene mayor simetría 

Se expresan las proteínas, se purifican se cristalizan.

- La celda unitaria 
    - unidad minima definida en xy y z que se necesita para reconsturir el cristal completo. 
        - si lo trasladas y lo rotas 
            - unidad asimétrica es mas chiva que la celda unitaria 
            - procesos de rotación y traslacion se genera el cristal entero 

- PSI Paul scharrer institut
    - Se generan los rayos X, se le disparan a los cristales de proteina acomodados de forma ordenada 
        - patrones de difracción se ven como puntitos 
            - se puede extraer el patrón que corresponde a las fases o amplitudes de esas ondas
                - se puede determinar la d
    - PX-2 


## Lyzosime 

## Life is the result of the chemical activity of proteins 

- spacefilling Representation 
    - radio de vanderballs es toda la probilidad de encontrar girando a las moléculas 
        - macromolecular crowding 
        - medir cosas con volumen 
        - 

space group es la constante unitaria 
- reflections on file 

[grupo de xds](https://www.biologie.uni-konstanz.de/diederichs/)



### Determinación de las bases con molecular replacement

projecto tutorial-LCG

seuqnce file lyzo.txt


### Molecular replacement


Data analysis 

- xtriage 
job:title: data analysys
    - xds_ascii.hkl

cuando nosotros le disparamos a un cristal de proteinas el cristal está girando 
entre más alejados estemos del centro es más alta la resolución 
entre más simetría puedes tener más redundancia 
    - mejora tu completness 
        - mosaicicidad es de mala calidad
            - redes internas en el cristal
    - buena calidad

le decimos que la

asmu le explicamos cuantas moleculas de lizosima tenemos por celda unitaria 
    - sabemos que hay 1 por cada celda unitaria 
    - add search templado 
        - le decimos que use la pdb 


## alpha trace C 

- carbobo alfa nos referimos al backbone de toda la proteína
    - son el esqueleto de la proteina
[Principles of protein structure, comparative portein modelling and visualization](https://swissmodel.expasy.org/course)

- peptide bond es en donde se unen dos resiudos
- beta sheet se ven com flechas 
- si queremos seguir el camino de la proteina desde el amino 
- carbox terminal inicia en rojo 
- amino terminal es el azul 

### Primary structure peptide bond 

20 aminoacidos naturales 
- glicina el más chico de la cadena lateral 
- alanina 
- valina 
- leucina 3 

- aromativos 
    - fenilalaninda

- positivas
    - histidina en mcuhas reacciones 

- polar sin carga 
    - prolina genera distorciones en las alfa helices 

- triptofano se usa en fluorescencia 

LA frecuencia de residuos como una función de su número de codones
- Ramachandran plot 

[Ramachandran plot](http://bioinformatics.org/molvis/phipsi/)

Radios de vander balls 
clash 
    - interacción fisicamente imposible 

- angulos phi y pshi
    - descripción de los grados de libertad que existene entre dos atomos 
    
solamente existen ciertas combinaciones de angulos phy y psi permitidos por los grados de libertad
    - cuando el phy esta en 0 no hay momento en el que el psi pueda existir sin clash

Se toma empiricamente y se cuantifican 

Tarea hacer el practice quiz de ramachandran plot

fenex refine 
- usa lo que le dimos 

[preguntas a contestar](https://cdn.rcsb.org/pdb101/molecular-machinery/)


Cuántas moléculas de miosina se necesitan para sostener una pelota de baseball.
Qué residuos forman el cromóforo de GFP
Cual es uno de los más poderosos inhibidores de la RNA polimerasa.
Describir la actividad de la DNA helicasa.
Que es mas grande un ribosoma o un virus?
Como funciona la lisozima

r-free score que no esta sesgado pues es solo 
bonds y angulos es que tan apretada está la proteina 
angulos la descripción geométrica de todos los ángulos 
- clashscore 
Ramachandran favored el 95% están cayendo en lasa regiones permitidas de la gráfica
- Ramachandran outliers:
    - alanina con un rotamero poco común 
    - 
phenix.refine 

Compare statistics 
-  lo que queremos tener es un pentagono simétrico 
    - 
    puente de hidrogeno son 2.5 armstrons 
    molecula de hibbs está funcionando como un amortiguador 


Tarea 3

corregir la lizosima 
- abrirla en coot
- jugar con los rotameros 
- resolver los clashes 
-tutorial-lcg_bad-atoms.pdb

- tiene interacciones 

validation en fenyx te dice qué aminoacidos tienen clash 
- clashcore 12 bajarlo como a 5.6 
- guardarlo como pdb y mandarlo 

